### ISSUE TITLE
Failed to install Saerileth v22 on latest https://github.com/EE-Mod-Setup/EE-Mod-Setup

### ISSUE THREAD

**Issue by simeonkosnitsky** [PaulaMigrate/Saerileth#2]
Failed to install Saerileth v22 on latest https://github.com/EE-Mod-Setup/EE-Mod-Setup
But successfully installed v21 after it.

```
[tb#_compile_eval_buffer/Saerileth/Scripts/SAERILET.baf] PARSE ERROR at line 1198 column 1-16
Near Text: )
[InParty] not found in ACTION.IDS
ERROR: parsing [tb#_compile_eval_buffer/Saerileth/Scripts/SAERILET.baf]: Parsing.Parse_error
ERROR: error compiling [tb#_compile_eval_buffer/Saerileth/Scripts/SAERILET.baf]: Parsing.Parse_error
ERROR: compiling [Saerileth/Scripts/SAERILET.baf]!
Stopping installation because of error.
```

[Setup-Saerileth.debug.log](https://github.com/PaulaMigrate/Saerileth/files/11444311/Setup-Saerileth.debug.log)
[EE-Debug-Installation.log](https://github.com/PaulaMigrate/Saerileth/files/11444306/EE-Debug-Installation.log)
[WeiDU.log](https://github.com/PaulaMigrate/Saerileth/files/11444307/WeiDU.log)
[WeiDU-BGEE.log](https://github.com/PaulaMigrate/Saerileth/files/11444308/WeiDU-BGEE.log)

**Comment by RoxanneSHS** [comment]
Fixed together with some other issues now.
